services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC receiver
      - "4318:4318"  # OTLP HTTP receiver
    depends_on:
      - tempo
      - loki
      - mimir

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo/tempo.yml"]
    volumes:
      - ./tempo.yml:/etc/tempo/tempo.yml
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"  # Tempo HTTP

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"  # Loki API (logs)
    command: -config.file=/etc/loki/local-config.yaml

  mimir:
    image: grafana/mimir:latest
    command: ["-target=all", "-config.file=/etc/mimir/mimir.yml"]
    volumes:
      - ./mimir.yml:/etc/mimir/mimir.yml
      - mimir-data:/var/mimir
    ports:
      - "9009:9009"  # Mimir HTTP
      - "9095:9095"  # Mimir gRPC

  grafana:
    image: grafana/grafana:12.3.1
    ports:
      - "3000:3000"  # Grafana UI (logs, metrics, traces)
    depends_on:
      - loki
      - mimir
      - tempo
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

volumes:
  tempo-data:
  mimir-data: