apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "structures-server.fullname" . }}
  labels:
    app: {{ include "structures-server.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "structures-server.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "structures-server.fullname" . }}
    namespace: {{ .Release.Namespace }}

