# General properties shared by all profiles
spring:
  main:
    web-application-type: none

logging:
  level:
    com:
      mindignited: INFO

structures:
  openApiSecurityType: BASIC
  enableStaticFileServer: true
  