# YAML Reference http://www.yaml.org/refcard.html
spring:
  main:
    web-application-type: none

logging:
  level:
    org:
      mindignited: TRACE

structures-migration:
  elasticScheme: "http"
  elasticHost: "localhost"
  elasticPort: "9200"